
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# logger: # https://www.home-assistant.io/integrations/logger/
#   default:  warn # debug, info, warn, warning, error, fatal, critical
#   logs:
#     homeassistant.components.http: debug

## Configure/Allow the reverse proxy
http:
  server_port: 80
  server_host:
    - 192.168.0.210 # same as in docker-compose.yml
    # - "hass.local" # check DNS to get the IP (resolves to same as 192.168.0.210, leading to duplicates and errors)
    # - "home.eckelt.info"
    
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.209
    # - 172.18.0.1      # from the error log
    # - 172.16.0.0/12   # docker range: 172.[17-31].0.0/16, see https://jodies.de/ipcalc?host=172.17.0.0&mask1=12&mask2=
    # - 192.168.0.0/16  # docker range: 192.168.[0-240].0/20 

  ip_ban_enabled: true
  login_attempts_threshold: 5