- id: '1706453201204'
  name: Rollos AUF
  entities:
    cover.rollo_buro:
      current_position: 100
      device_class: shutter
      friendly_name: Rollo B端ro
      supported_features: 15
      state: open
    cover.rollo_kuche:
      current_position: 100
      device_class: shutter
      friendly_name: Rollo K端che
      supported_features: 15
      state: open
    cover.rollo_sz:
      current_position: 100
      device_class: shutter
      friendly_name: Rollo SZ
      supported_features: 15
      state: open
    cover.rollo_wz:
      current_position: 100
      device_class: shutter
      friendly_name: Rollo WZ
      supported_features: 15
      state: open
  icon: mdi:archive-arrow-up
  metadata: {}
- id: '1706453331054'
  name: Rollos ZU
  entities:
    cover.rollo_buro:
      current_position: 0
      device_class: shutter
      friendly_name: Rollo B端ro
      supported_features: 15
      state: closed
    cover.rollo_kuche:
      current_position: 0
      device_class: shutter
      friendly_name: Rollo K端che
      supported_features: 15
      state: closed
    cover.rollo_sz:
      current_position: 0
      device_class: shutter
      friendly_name: Rollo SZ
      supported_features: 15
      state: closed
    cover.rollo_wz:
      current_position: 0
      device_class: shutter
      friendly_name: Rollo WZ
      supported_features: 15
      state: closed
  metadata: {}
  icon: mdi:archive-arrow-down
